"""biopsy init — starter TOML generation."""

from __future__ import annotations

from pathlib import Path

import typer
from rich.console import Console

import biopsy.cli as cli
from biopsy.cli.common import print_artifact_path, write_text_artifact
from biopsy.inference import infer_excludes, infer_target, infer_time


def init_config_cmd(
    path: Path = typer.Argument(..., help="Dataset to inspect for config defaults."),
    output: Path = typer.Option(
        Path("biopsy.toml"), "--output", "-o", help="Config file to write."
    ),
    target: str | None = typer.Option(None, "--target", "-t", help="Target column to write."),
    time_col: str | None = typer.Option(None, "--time", help="Time column to write."),
    sample: int = typer.Option(10_000, "--sample", min=1, help="Rows to sample for inference."),
    overwrite: bool = typer.Option(False, "--overwrite", help="Replace an existing config file."),
) -> None:
    """Infer a starter biopsy.toml from a dataset."""
    output = output.expanduser().resolve()
    if output.exists() and not overwrite:
        raise typer.BadParameter(f"{output} already exists; pass --overwrite to replace it.")

    src = cli.load(path, sample=sample)
    try:
        stats = cli.compute_all(src)
    finally:
        src.con.close()
    if target is not None and target not in stats:
        raise typer.BadParameter(f"Target column '{target}' not found in {path}.")
    if time_col is not None and time_col not in stats:
        raise typer.BadParameter(f"Time column '{time_col}' not found in {path}.")

    inferred_target = target or infer_target(stats)
    inferred_time = time_col or infer_time(stats)
    excludes = infer_excludes(stats, target=inferred_target, time_col=inferred_time)

    output = write_text_artifact(
        output,
        init_config_text(
            source=path,
            target=inferred_target,
            time_col=inferred_time,
            excludes=excludes,
        ),
    )

    console = Console()
    print_artifact_path(console, "Wrote", output)
    if inferred_target:
        console.print(f"[dim]Target:[/dim] {inferred_target}")
    if inferred_time:
        console.print(f"[dim]Time:[/dim] {inferred_time}")
    if excludes:
        console.print(f"[dim]Excludes:[/dim] {', '.join(excludes[:12])}")


def init_config_text(
    *,
    source: Path,
    target: str | None,
    time_col: str | None,
    excludes: list[str],
) -> str:
    lines = [
        "# Generated by `biopsy init`.",
        f"# Source inspected: {source.expanduser()}",
        "",
    ]
    if target:
        lines.append(f"target = {toml_string(target)}")
    else:
        lines.append('# target = "your_target_column"')
    if time_col:
        lines.append(f"time = {toml_string(time_col)}")
    else:
        lines.append('# time = "your_time_column"')
    lines.extend(
        [
            f"exclude = {toml_string_list(excludes)}",
            "filter = []",
            "fast = true",
            "target_sample = 30000",
            "ignore_missing_exclude = true",
            "plotly_cdn = true",
            "",
            "[profiles.deep]",
            "fast = false",
            "target_sample = 50000",
        ]
    )
    return "\n".join(lines) + "\n"


def toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def toml_string_list(values: list[str]) -> str:
    if not values:
        return "[]"
    return "[" + ", ".join(toml_string(value) for value in values) + "]"
